name: pingsite
description: Never miss a crash

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  phoenix_wings: ^1.0.2
  cupertino_icons: ^1.0.3
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  flutter_secure_storage: ^5.0.2
  animated_widgets: ^1.1.0
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.10
  flutter_local_notifications: ^9.4.0
  firebase_analytics: ^9.1.2
  device_info_plus: ^3.2.2
  uuid: ^3.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/launcher_icon/ios.png"
  image_path_android: "assets/launcher_icon/android.png"
