// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6601w9mrzegBhmcrMvrKDZ2LHfvWzFQY',
    appId: '1:717091205676:web:73420b6b2ef69ec8871789',
    messagingSenderId: '717091205676',
    projectId: 'pingsite-fb',
    authDomain: 'pingsite-fb.firebaseapp.com',
    storageBucket: 'pingsite-fb.appspot.com',
    measurementId: 'G-S90G6L1VMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMDd7b3UmJU-XUfKpXBGobzlg1iKAHEQ',
    appId: '1:717091205676:android:4a674c33dc27c088871789',
    messagingSenderId: '717091205676',
    projectId: 'pingsite-fb',
    storageBucket: 'pingsite-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHR77Z_ijLNnWXWQGzLW-PFLVyweSRG1U',
    appId: '1:717091205676:ios:bdab4f8a5e275f71871789',
    messagingSenderId: '717091205676',
    projectId: 'pingsite-fb',
    storageBucket: 'pingsite-fb.appspot.com',
    androidClientId: '717091205676-nfo675slg73p1hdu2ok9h800ojcffsoo.apps.googleusercontent.com',
    iosClientId: '717091205676-mo7ibt3h7ebn3uu9u522rc2ef744ncuh.apps.googleusercontent.com',
    iosBundleId: 'com.podnoms.pingsite',
  );
}
